
name: expert pancake
Pull Request

on:
  pull_request_target:
    types: [if neccessary]

jobs:
  close_job:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == true/false
    if false auto fix issues and merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['']
            })
